springdoc:
  show-login-endpoint: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: Auth Service
        url: /api/auth/v3/api-docs
      - name: Customer Service
        url: /api/customer/v3/api-docs
